services:
  ecommerce.api:
    image: ecommerceapi
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile
    ports:
      - "7001:8080"
    environment:
      - MONGO_HOST=mongodb-container
      - MONGO_PORT=27017
      - MONGODB_DATABASE=OrdersDatabase
      - UsersMicroserviceName=users-microservice
      - UsersMicroservicePort=9090
      - ProductsMicroserviceName=products-microservice
      - ProductsMicroservicePort=8080
    networks:
      - order-mongo-db-network
      - ecommerce-network
    depends_on:
      - mongodb-container
      - users-microservice

  mongodb-container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ../DatabaseQuery/orders-init:/docker-entrypoint-initdb.d
    networks:
      - order-mongo-db-network

  products-microservice:
    image: products-microservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - MYSQL_HOSTNAME=mysql-container
      - MYSQL_PORT=3306
      - MYSQL_Password=admin
      - MYSQL_DATABASE=ecommerceproductsdatabase
      - MYSQL_USER=root
    ports:
      - "6001:8080"
    networks:
      - product-mysql-db-network
      - ecommerce-network
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - ../DatabaseQuery/products-init:/docker-entrypoint-initdb.d
    networks:
      - product-mysql-db-network
    command: --lower_case_table_names=1

  users-microservice:
    image: users-microservice:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=9090
      - POSTGRES_HOSTNAME=postgres-container
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=eCommerceUsers
      - POSTGRES_USER=postgres
    ports:
      - "5001:9090"
    networks:
      - user-postgres-db-network
      - ecommerce-network
    depends_on:
      - postgres-container

  postgres-container:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: eCommerceUsers
    ports:
      - "5433:5432"
    volumes:
      - ../DatabaseQuery/users-init:/docker-entrypoint-initdb.d
    networks:
      - user-postgres-db-network

networks:
  order-mongo-db-network:
    driver: bridge
  product-mysql-db-network:
    driver: bridge
  user-postgres-db-network:
    driver: bridge
  ecommerce-network:
    driver: bridge