<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f099e783-642f-4e48-acf4-8d790a98e8d0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.BusinessLogicLayer\Ecommerce.BusinessLogicLayer.csproj" />
  </ItemGroup>

</Project>
