global using Ecommerce.API.APIEndpoints;
global using Ecommerce.API.Handlers;
global using Ecommerce.BusinessLogicLayer;
global using Ecommerce.BusinessLogicLayer.DTO;
global using Ecommerce.BusinessLogicLayer.ServiceContracts;
global using Ecommerce.DataAccessLayer;
global using Ecommerce.DataAccessLayer.Entities;
global using FluentValidation;
global using FluentValidation.Results;
